name: go_mart
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.10.1

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    flutter_animate: ^4.5.2
    collection: ^1.19.1
    flutter_hooks: ^0.21.3+1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/fonts/
        - assets/

    fonts:
        - family: Outfit
          fonts:
              - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf
                weight: 100
              - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
                weight: 200
              - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
                weight: 300
              - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
                weight: 400
              - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
                weight: 500
              - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
                weight: 700
              - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
                weight: 800
              - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
                weight: 900
